In [1]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn.metrics import auc
from sklearn.metrics import plot_roc_curve
from sklearn.model_selection import StratifiedKFold
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from random import shuffle
from scipy.stats import ranksums
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score

In [2]:
# Defino variables donde voy a ir a poner cosas 
acc = []
acc_sh = []
cm = np.zeros((2,2))
cm_sh = np.zeros((2,2))
features_selected = np.zeros(100)
features_selected_sh = np.zeros(100)

numfeat = 50 # numero de features para usar con feature selection univariado 


In [3]:

# Este codigo existe para seleccionar un threshold que haga a las matrices de confusion lo mas diagonales posibles
def diag_cm(classifier, X_test_new): 
    thr = np.arange(0,1,0.1)
    opt = 10*len(X_test_new)
    for t in thr:
        pred = classifier.predict_proba(X_test_new)[:,1]>t
        cm_temp = np.double(np.array(confusion_matrix(y[test],pred)))
        opt_temp = np.abs(cm_temp[0,0] - cm_temp[1,1])+cm_temp[0,1]+cm_temp[1,0]
        if opt_temp<opt:
            cm_out = cm_temp
            opt=opt_temp
           # print(opt)
           # print(cm_out)
    return cm_out




## Cargar los datos

In [4]:
# 1. cargo la matriz con features

#DATA CN DEBERIA SER DATOS DE PERSONAS SANAS Y CON LOS MISMOS FEATURES QUE LAS PERSONAS ENFERMAS, ICTAL
data_CN = np.array(pd.read_csv('C:\PAO\proyecto/InterIctalA.csv', delimiter=',',header=0))
data_AD = np.array(pd.read_csv('C:\PAO\proyecto/Ictal2.csv',delimiter=',',header=0))

data_CN = np.delete(data_CN, 0, 1)
data_AD = np.delete(data_AD, 0, 1)

print(data_CN)
print(data_AD)

[[  0.82872823   0.55658427   0.51813273   0.81847993   0.76106143
    0.23264412   3.8797301   83.           1.01624687   2.40871208
    1.29684207   1.39661611]
 [  0.82019924   0.63590208   0.58239609   0.90858102   0.91530917
    0.30229493   2.59823492  88.           1.01556853   2.32371155
    1.30156915   1.18732333]
 [  0.78588985   0.59862576   0.55779447   0.70629813   0.66330522
    0.28511477   2.4739528   89.           1.01367854   2.26031552
    1.24199278   1.2121708 ]
 [  0.81586936   0.62183218   0.5839388    0.83266139   0.80135961
    0.29852299   2.79385918  86.           1.01535937   2.71375483
    1.29315939   1.22915446]
 [  0.80440173   0.61361689   0.5741564    0.84274555   0.80000011
    0.28882236   2.87961423  94.           1.01452064   2.56231832
    1.33145956   1.25376983]
 [  0.81512107   0.63242615   0.60370757   0.82836837   0.80739462
    0.32452426   2.46065586  91.           1.01551626   2.12831235
    1.3100793    1.13967981]
 [  0.8565701    0.625

## Crear vectores y asignar labels

In [5]:
# 2. Crear matriz con clases
y_CN = np.zeros(data_CN.shape[0])
y_AD = np.ones(data_AD.shape[0])

y = np.concatenate((y_CN,y_AD))
X = np.concatenate((data_CN,data_AD))

# X datos matriz de features
# y vector de etiquetas

print("MATRIZ DE FEATURES")
print(X)

print("VECTOR DE ETIQUETAS")
print(y)

MATRIZ DE FEATURES
[[0.82872823 0.55658427 0.51813273 ... 2.40871208 1.29684207 1.39661611]
 [0.82019924 0.63590208 0.58239609 ... 2.32371155 1.30156915 1.18732333]
 [0.78588985 0.59862576 0.55779447 ... 2.26031552 1.24199278 1.2121708 ]
 ...
 [0.64959457 0.47716719 0.4458073  ... 2.43123945 1.20734358 1.46841019]
 [0.73646508 0.35493727 0.39069644 ... 2.2627397  1.17585623 1.64797913]
 [0.76228874 0.50865544 0.49326597 ... 1.94938296 1.26711314 1.42967687]]
VECTOR DE ETIQUETAS
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


## Generar Esquema de particion - Cross Validation

In [1]:
folds = 5 # folds de la validacion cruzada 5 es un valor standar (con)
iterations = 100 # itereaciones con para estimar el p-value con random shuffling de las etiquetas

## ESTO SI
# defino el clasificador (es un Gradient Boosting Classifier, similar a Random Forest)
classifier = GradientBoostingClassifier(n_estimators=1000,learning_rate= 0.01, max_features= 2)

all_tprs = []
all_aucs = []

mean_fpr = np.linspace(0, 1, 1000) # esto sirve para plotear el ROC 

##Optional
print(all_tprs)
print(all_aucs)
print(folds)


NameError: name 'GradientBoostingClassifier' is not defined